FROM node:20.15.0-alpine3.20

EXPOSE 8080
ENV DB_HOST=mysql

RUN addgroup -S campusease && adduser -S campusease -G campusease \
    && mkdir /opt/server \
    && chown campusease:campusease -R /opt/server

WORKDIR /opt/server

COPY package.json ./
COPY *.js /opt/server/

RUN npm install

USER campusease

CMD [ "node", "index.js" ]
