apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: seatfinder-hpa
  labels:
    app: seatfinder
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: seatfinder-deploy
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 65
